### ISSUE TITLE
Better support for dark mode highlight

### ISSUE THREAD

**Issue by kinalmehta** [DenaroCF/Highlighters-for-Logseq#3]
Thanks for this awesome work.

Currently the highlight in dark mode makes the text unreadable. Can it be updated with some better combination?
I could try some combinations and update here.

Also could you request this to be included in the logseq plugins marketplace?

Thanks

**Comment by DenaroCF** [comment]
Hi! You can change the colors by making some tweaks in your custom.css (I put some colors just as a functional template). I'll upload it to the marketplace this weekend.

Thx :)
